apiVersion: v1
data:
  filePath: sample-deploy.yaml
  source: 'https://github.com/maheshopsmx/jmeter.git'
  sourcebranch: main
  target: 'https://github.com/maheshopsmx/jmeter.git'
  value: >-
    .metadata.annotations.jiraid = "${ parameters["JIRAID"]}"|.spec.replicas =
    ${ parameters["replicaCount"]}|.spec.template.spec.containers[0].image = "${
    parameters["IMAGEID"]}"
kind: ConfigMap
metadata:
  name: spin2argo-config
